'use server';

/**
 * @fileOverview An AI tool that intelligently merges two daily plans into a single, cohesive schedule.
 *
 * - mergeDailyPlans - A function that combines an existing plan and a new plan.
 * - MergeDailyPlansInput - The input type for the mergeDailyPlans function.
 * - MergeDailyPlansOutput - The return type for the mergeDailyPlans function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const ActivitySchema = z.object({
    time: z.string().describe('The time for the activity, e.g., "09:00 - 10:30".'),
    activity: z.string().describe('The description of the activity.'),
});

const MergeDailyPlansInputSchema = z.object({
  existingPlan: z.array(ActivitySchema).describe('The user’s current plan for the day.'),
  newPlan: z.array(ActivitySchema).describe('The new plan generated by the AI that needs to be merged.'),
});
export type MergeDailyPlansInput = z.infer<typeof MergeDailyPlansInputSchema>;

const MergeDailyPlansOutputSchema = z.object({
  mergedPlan: z.array(ActivitySchema).describe('A single, cohesive, and chronologically sorted list of activities for the day.'),
});
export type MergeDailyPlansOutput = z.infer<typeof MergeDailyPlansOutputSchema>;

export async function mergeDailyPlans(input: MergeDailyPlansInput): Promise<MergeDailyPlansOutput> {
  return mergeDailyPlansFlow(input);
}

const prompt = ai.definePrompt({
  name: 'mergeDailyPlansPrompt',
  input: { schema: MergeDailyPlansInputSchema },
  output: { schema: MergeDailyPlansOutputSchema },
  prompt: `You are a master scheduler AI. Your task is to intelligently merge two daily plans into a single, cohesive, and chronologically sorted schedule.

  Rules:
  1.  **Resolve Conflicts:** If there are overlapping time slots, prioritize the item from the "new plan" unless the "existing plan" item seems critically important (like a fixed appointment or class). Adjust surrounding flexible tasks if necessary.
  2.  **Combine Similar Activities:** If both plans have similar activities around the same time (e.g., "Lunch" and "Eat Lunch"), combine them into a single entry.
  3.  **Maintain Chronological Order:** The final merged plan must be sorted by time from the beginning to the end of the day.
  4.  **Do Not Drop Important Items:** Ensure all unique and important activities from both plans are included in the final output.
  5.  **Be Logical:** Create a schedule that flows naturally.

  **Existing Plan:**
  {{#each existingPlan}}
  - {{this.time}}: {{this.activity}}
  {{/each}}

  **New Plan to Merge:**
  {{#each newPlan}}
  - {{this.time}}: {{this.activity}}
  {{/each}}

  Generate the merged plan.
  `,
});

const mergeDailyPlansFlow = ai.defineFlow(
  {
    name: 'mergeDailyPlansFlow',
    inputSchema: MergeDailyPlansInputSchema,
    outputSchema: MergeDailyPlansOutputSchema,
  },
  async (input) => {
    const { output } = await prompt(input);
    return output!;
  }
);
